version: "3.9"
services:
  backend:
    build: ./movie-app-backend
    container_name: movie-backend
    ports:
      - "8000:8000"
    volumes:
      - ./movie-app-backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: movie-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
